console.log('getting data');
globalThis.convertibleIngredients = [
  {
    mainName: 'Brown Sugar',
    names: ['brown sugar'],
    cups: 180,
    tbsp: 11.25,
    tsp: 3.75,
  },
  {
    mainName: 'Powdered Sugar',
    names: ['powdered sugar', 'confectioner sugar'],
    cups: 200,
    tbsp: 12.5,
    tsp: 4.2,
  },
  {
    mainName: 'Granulated Sugar',
    names: ['granulated sugar', 'white sugar', 'sugar'],
    cups: 200,
    tbsp: 12.5,
    tsp: 4.2,
  },
  {
    mainName: 'Sifted Flour',
    names: [
      'sifted flour',
      'sifted ap flour',
      'sifted all purpose flour',
      'sifted all-purpose flour',
      'sifted ap-four',
    ],
    cups: 110,
    tbsp: 6.8,
    tsp: 2.3,
  },
  {
    mainName: 'Self-Rising Flour',
    names: ['self-rising flour', 'self rising flour'],
    cups: 113,
    tbsp: 7.06,
    tsp: 235,
  },
  {
    mainName: 'All-Purpose Flour',
    names: [
      'ap flour',
      'all purpose flour',
      'all-purpose flour',
      'ap-four',
      'flour',
    ],
    cups: 120,
    tbsp: 7.5,
    tsp: 2.5,
  },
  {
    mainName: 'Baking Powder',
    names: ['baking powder'],
    cups: 192,
    tbsp: 12,
    tsp: 4,
  },
  {
    mainName: 'Baking Soda',
    names: ['baking soda'],
    cups: 144,
    tbsp: 9,
    tsp: 3,
  },
  {
    mainName: 'buttermilk',
    names: ['buttermilk'],
  },
  {
    mainName: 'Butter',
    names: ['butter'],
    cups: 226,
    sticks: 113,
    tbsp: 14.125,
  },
  {
    mainName: 'Cornmeal',
    names: ['cornmeal', 'corn meal'],
    cups: 170,
    tbsp: 10.63,
    tsp: 3.54,
  },
  {
    mainName: 'Cocoa Powder',
    names: ['cocoa'],
    cups: 113.4,
    tbsp: 14.17,
    tsp: 4.72,
  },
  {
    mainName: 'Corn Starch',
    names: ['cornstarch', 'cornstarch'],
    cups: 127.57,
    tbsp: 7.97,
    tsp: 2.66,
  },
];
globalThis.measurements = {
  tbsp: ['tbsp', 'tablespoons', 'tablespoon', 'tbsp.'],
  cups: ['cups', 'cup', 'cps', 'c.'],
  tsp: ['tsp', 'teaspoons', 'teaspoon', 'tsp.'],
  sticks: ['stick', 'sticks'],
};

globalThis.fractionChars = {
  188: 0.25,
  189: 0.5,
  190: 0.75,
  8528: 0.14,
  8529: 0.11,
  8530: 0.1,
  8531: 0.33,
  8532: 0.67,
  8533: 0.2,
  8534: 0.4,
  8535: 0.6,
  8536: 0.8,
  8537: 0.17,
  8538: 0.83,
  8539: 0.13,
  8540: 0.38,
  8541: 0.63,
  8542: 0.88,
};
